---
version: 2
before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
upx:
  - enabled: true
    compress: "1"
archives:
  - format_overrides:
      - goos: windows
        format: zip
dockers:
  - use: buildx
    image_templates:
    - "ghcr.io/devopshivehq/kube-rbac-extractor:latest-amd64"
    - "ghcr.io/devopshivehq/kube-rbac-extractor:{{ .Major }}-amd64"
    - "ghcr.io/devopshivehq/kube-rbac-extractor:{{ .Major }}.{{ .Minor }}-amd64"
    - "ghcr.io/devopshivehq/kube-rbac-extractor:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-amd64"
    build_flag_templates:
    - "--pull"
    - "--platform=linux/amd64"
    # OCI annotations: https://github.com/opencontainers/image-spec/blob/main/annotations.md
    - "--label=org.opencontainers.image.created={{ .Date }}"
    - "--label=org.opencontainers.image.name={{ .ProjectName }}"
    - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
    - "--label=org.opencontainers.image.version={{ .Version }}"
    - "--label=org.opencontainers.image.source={{ .GitURL }}"
  - use: buildx
    image_templates:
    - "ghcr.io/devopshivehq/kube-rbac-extractor:latest-arm64"
    - "ghcr.io/devopshivehq/kube-rbac-extractor:{{ .Major }}-arm64"
    - "ghcr.io/devopshivehq/kube-rbac-extractor:{{ .Major }}.{{ .Minor }}-arm64"
    - "ghcr.io/devopshivehq/kube-rbac-extractor:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-arm64"
    build_flag_templates:
    - "--pull"
    - "--platform=linux/arm64"
    # OCI annotations: https://github.com/opencontainers/image-spec/blob/main/annotations.md
    - "--label=org.opencontainers.image.created={{ .Date }}"
    - "--label=org.opencontainers.image.name={{ .ProjectName }}"
    - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
    - "--label=org.opencontainers.image.version={{ .Version }}"
    - "--label=org.opencontainers.image.source={{ .GitURL }}"
docker_manifests:
  - name_template: "ghcr.io/devopshivehq/kube-rbac-extractor:latest"
    image_templates:
    - "ghcr.io/devopshivehq/kube-rbac-extractor:latest-amd64"
    - "ghcr.io/devopshivehq/kube-rbac-extractor:latest-arm64"
  - name_template: "ghcr.io/devopshivehq/kube-rbac-extractor:{{ .Major }}"
    image_templates:
    - "ghcr.io/devopshivehq/kube-rbac-extractor:{{ .Major }}-amd64"
    - "ghcr.io/devopshivehq/kube-rbac-extractor:{{ .Major }}-arm64"
  - name_template: "ghcr.io/devopshivehq/kube-rbac-extractor:{{ .Major }}.{{ .Minor }}"
    image_templates:
    - "ghcr.io/devopshivehq/kube-rbac-extractor:{{ .Major }}.{{ .Minor }}-amd64"
    - "ghcr.io/devopshivehq/kube-rbac-extractor:{{ .Major }}.{{ .Minor }}-arm64"
  - name_template: "ghcr.io/devopshivehq/kube-rbac-extractor:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
    image_templates:
    - "ghcr.io/devopshivehq/kube-rbac-extractor:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-amd64"
    - "ghcr.io/devopshivehq/kube-rbac-extractor:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-arm64"
release:
  github: {}
  name_template: "{{ .Version }}"
  prerelease: auto
  mode: append
signs:
  - cmd: cosign
    env:
      - COSIGN_EXPERIMENTAL=1
    certificate: '${artifact}.pem'
    args:
      - sign-blob
      - '--yes'
      - '--output-certificate=${certificate}'
      - '--output-signature=${signature}'
      - '${artifact}'
    artifacts: checksum
    output: true
docker_signs:
  - cmd: cosign
    env:
      - COSIGN_EXPERIMENTAL=1
    args:
      - sign
      - '--yes'
      - '${artifact}'
    artifacts: all
    output: true
# Changelog is generated by release-please.
changelog:
  disable: true
