name: Go - Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch: { }

permissions:
  contents: read

jobs:
  release:
    name: Release
    permissions:
      contents: write
      id-token: write
      packages: write
      pull-requests: write
    uses: ./.github/workflows/tpl-packaging.yml
    secrets: inherit
    with:
      goreleaser-args: "release --clean"
